// Generated by CoffeeScript 1.6.2
var assert, async, path, toType;

assert = require('chai').assert;

async = require('async');

path = require('path');

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

describe('GeneralConfiguration', function() {
  var GeneralConfiguration;

  GeneralConfiguration = require('../src/GeneralConfiguration');
  it('Should be a GeneralConfiguration', function() {
    return assert.equal(GeneralConfiguration.prototype.GeneralConfiguration, true);
  });
  return describe('_constructor_', function() {
    return it('Should have a _constructor_', function() {
      return assert.typeOf(GeneralConfiguration.prototype._constructor_, 'function');
    });
  });
});
