// Generated by CoffeeScript 1.6.2
var assert, async, path, toType;

assert = require('chai').assert;

async = require('async');

path = require('path');

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

describe('GeneralConfiguration', function() {
  var GeneralConfiguration;

  return GeneralConfiguration = require('../src/GeneralConfiguration');
});
