// Generated by CoffeeScript 1.6.2
var assert, async, path;

assert = require('chai').assert;

async = require('async');

path = require('path');

describe('Jelly', function() {
  var Jelly;

  Jelly = require('../src/Jelly');
  describe('#constructor', function() {
    it('creating a Jelly instance should not throw errors', function() {
      var jelly;

      return jelly = new Jelly();
    });
    return it('Jelly should inherits from a Logger', function() {
      return assert.equal(Jelly.prototype.Logger, true);
    });
  });
  describe('#getRootDirectory', function() {
    it('Should be a callable function', function() {
      return assert.typeOf(Jelly.prototype.getRootDirectory, "function");
    });
    it('Should return __dirname by default', function() {
      var dirname, jelly;

      jelly = new Jelly();
      dirname = path.normalize("" + __dirname + "/../src");
      return assert.equal(jelly.getRootDirectory(), dirname, "the directory should be __dirname");
    });
    return it('Should get the current root directory', function() {
      var jelly;

      jelly = new Jelly();
      jelly.setRootDirectory('a');
      assert.equal(jelly.getRootDirectory(), 'a', 'the current root directory is not what specified');
      jelly.setRootDirectory('b');
      return assert.equal(jelly.getRootDirectory(), 'b', 'the current root directory is not what specified');
    });
  });
  return describe('#setRootDirectory', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(Jelly.prototype.getRootDirectory, "function");
    });
  });
});
