// Generated by CoffeeScript 1.6.2
var assert, async;

assert = require('chai').assert;

async = require('async');

describe('Logger', function() {
  var Logger;

  Logger = require('../src/Logger');
  describe('#constructor', function() {
    return it('creating a Logger should not throw errors', function() {
      var logger;

      return logger = new Logger();
    });
  });
  it('Should be an instance of Logger', function() {
    return assert.equal(new Logger().Logger, true);
  });
  describe('#getLogger()', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(new Logger().getLogger, "function");
    });
  });
  describe('#info', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(new Logger().getLogger().info, "function");
    });
  });
  describe('#log', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(new Logger().getLogger().log, "function");
    });
  });
  describe('#error', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(new Logger().getLogger().error, "function");
    });
  });
  return describe('#warn', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(new Logger().getLogger().warn, "function");
    });
  });
});
