// Generated by CoffeeScript 1.6.2
var assert, async, path, toType;

assert = require('chai').assert;

async = require('async');

path = require('path');

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

describe('PluginWrapper', function() {
  var PluginWrapper;

  PluginWrapper = require('../src/PluginWrapper');
  it('Should be a PluginWrapper', function() {
    return assert.equal(PluginWrapper.prototype.PluginWrapper, true);
  });
  describe('_constructor_', function() {
    return it('Should have a _constructor_', function() {
      return assert.typeOf(PluginWrapper.prototype._constructor_, 'function');
    });
  });
  return describe('applyPlugin', function() {
    return it('Should be a callable function', function() {
      return assert.typeOf(PluginWrapper.prototype.applyPlugin, 'function');
    });
  });
});
