// Generated by CoffeeScript 1.6.2
var GeneralConfiguration, Jelly, assert, async, path, toType;

assert = require('chai').assert;

async = require('async');

path = require('path');

toType = function(obj) {
  return {}.toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};

Jelly = require('../src/Jelly');

GeneralConfiguration = require('../src/GeneralConfiguration');

describe('PluginDirectory', function() {
  var PluginDirectory;

  PluginDirectory = require('../src/PluginDirectory');
  it('Should be a PluginDirectory', function() {
    return assert.equal(PluginDirectory.prototype.PluginDirectory, true);
  });
  return describe('#', function() {});
});
