// Generated by CoffeeScript 1.6.2
var assert;

assert = require('chai').assert;

describe('ReadableEntity', function() {
  var ReadableEntity;

  ReadableEntity = require('../src/ReadableEntity');
  describe('#constructor', function() {
    return it('creating a ReadableEntity should not throw errors', function() {
      var readableEntity;

      return readableEntity = new ReadableEntity();
    });
  });
  return describe('#getCurrentContent', function() {
    it('Should be a callable function', function() {
      return assert.typeOf(new ReadableEntity().getCurrentContent, "function");
    });
    it('Should return an empty object when nothing is set', function() {
      var readableEntity;

      readableEntity = new ReadableEntity();
      return assert.equal(JSON.stringify(readableEntity.getCurrentContent()), "{}");
    });
    return it('Should get the last content pushed', function() {
      var lastContent, readableEntity;

      readableEntity = new ReadableEntity();
      assert.typeOf(readableEntity.updateContent, "function", "updateContent is not callable");
      readableEntity.updateContent({
        content: "Test1"
      });
      lastContent = readableEntity.getCurrentContent();
      assert.typeOf(lastContent, "object", "updateContent did not return a valid content");
      assert.typeOf(lastContent.content, "string", "updateContent returned the wrong content");
      assert.equal(lastContent.content, "Test1", "updateContent returned the wrong content");
      readableEntity.updateContent({
        content: "Test2"
      });
      lastContent = readableEntity.getCurrentContent();
      assert.typeOf(lastContent, "object", "updateContent did not return a valid content");
      assert.typeOf(lastContent.content, "string", "updateContent returned the wrong content");
      assert.equal(lastContent.content, "Test2", "updateContent returned the wrong content");
      readableEntity.updateContent({
        content: "Test3"
      });
      lastContent = readableEntity.getCurrentContent();
      assert.typeOf(lastContent, "object", "updateContent did not return a valid content");
      assert.typeOf(lastContent.content, "string", "updateContent returned the wrong content");
      return assert.equal(lastContent.content, "Test3", "updateContent returned the wrong content");
    });
  });
});
