// Generated by CoffeeScript 1.6.2
var curExport, exportList, exportObject, srcDirectory, _i, _len;

srcDirectory = __dirname + '/src/';

exportList = ['Events', 'File', 'GeneralConfiguration', 'Jelly', 'Logger', 'Module', 'PluginDirectory', 'PluginHandler', 'PluginInterface', 'PluginWrapper', 'ReadableEntity', 'SharedObject', 'SharedObjectManager', 'Tools', 'TreeElement'];

exportObject = {};

for (_i = 0, _len = exportList.length; _i < _len; _i++) {
  curExport = exportList[_i];
  exportObject[curExport] = require("" + srcDirectory + "/" + curExport);
}

module.exports = exportObject;
