// Generated by CoffeeScript 1.6.2
var Mocha, async, fs, mocha, rootDir;

Mocha = require('mocha');

fs = require('fs');

async = require('async');

mocha = new Mocha();

rootDir = __dirname;

async.series([
  function(cb) {
    var dir;

    dir = "" + rootDir + "/test";
    return fs.readdir(dir, function(err, files) {
      var file, _i, _len;

      if (err != null) {
        cb(err);
        return;
      }
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if (/\.js$/.test(file)) {
          mocha.addFile("" + dir + "/" + file);
        }
      }
      return cb();
    });
  }, function(cb) {
    var dir;

    dir = "" + rootDir + "/src/plugins";
    return fs.readdir(dir, function(err, files) {
      if (err) {
        cb(err);
        return;
      }
      return async.map(files, function(folder, cb) {
        var curDir;

        curDir = "" + dir + "/" + folder + "/test";
        return fs.readdir(curDir, function(err, files) {
          var file, _i, _len;

          if (err) {
            cb();
            return;
          }
          for (_i = 0, _len = files.length; _i < _len; _i++) {
            file = files[_i];
            if (/\.js$/.test(file)) {
              mocha.addFile("" + curDir + "/" + file);
            }
          }
          cb();
        });
      }, function(err) {
        return cb(err);
      });
    });
  }, function(cb) {
    var runner;

    return runner = mocha.run(function(e) {
      return process.exit(e);
    });
  }
], function(err) {
  if (err) {
    return process.exit(1);
  }
});
