// Generated by CoffeeScript 1.6.2
var GeneralConfiguration, Logger, ReadableEntity, Tools, TreeElement, _GeneralConfiguration;

ReadableEntity = require('./ReadableEntity');

Tools = require('./Tools');

TreeElement = require('./TreeElement');

Logger = require('./Logger');

/**
 * GeneralConfiguration is a class dealing with GeneralConfiguration files
 * The main goal of this class is to provide read and process general configuration files
 * 
 * @class GeneralConfiguration
 * @extends Logger
 * @extends ReadableEntity
 * @extends TreeElement
*/


GeneralConfiguration = Tools.implementing(Logger, ReadableEntity, TreeElement, _GeneralConfiguration = (function() {
  function _GeneralConfiguration() {}

  return _GeneralConfiguration;

})(), GeneralConfiguration = (function() {
  GeneralConfiguration.prototype.GeneralConfiguration = true;

  function GeneralConfiguration() {
    this._constructor_();
  }

  GeneralConfiguration.prototype._constructor_ = function() {};

  return GeneralConfiguration;

})());

module.exports = GeneralConfiguration;
