// Generated by CoffeeScript 1.6.2
var Logger, WinstonLoggerWrapper, winston;

winston = require('winston');

WinstonLoggerWrapper = (function() {
  WinstonLoggerWrapper.prototype._constructor_ = function() {
    this._logger = new winston.Logger();
    this._logger.add(winston.transports.Console);
    this._name = '';
    return this._object = null;
  };

  function WinstonLoggerWrapper() {
    this._constructor_();
  }

  WinstonLoggerWrapper.prototype.LoggerWrapper = true;

  WinstonLoggerWrapper.prototype.setClassName = function(name) {
    return this._name = name;
  };

  WinstonLoggerWrapper.prototype.setObject = function(obj) {
    return this._object = obj;
  };

  WinstonLoggerWrapper.prototype.getPrintHeader = function() {
    var id;

    id = '';
    if ((this._object != null) && typeof this._object.getId === 'function' && this._object.getId() !== null) {
      id = '[' + this._object.getId() + ']';
    }
    return (this._name || '') + id + ': ';
  };

  WinstonLoggerWrapper.prototype.info = function(s) {
    return this._logger.info(this.getPrintHeader() + s);
  };

  WinstonLoggerWrapper.prototype.log = function(type, s) {
    return this._logger.log(type, this.getPrintHeader() + s);
  };

  WinstonLoggerWrapper.prototype.error = function(s) {
    return this._logger.error(this.getPrintHeader() + s);
  };

  WinstonLoggerWrapper.prototype.warn = function(s) {
    return this._logger.warn(this.getPrintHeader() + s);
  };

  WinstonLoggerWrapper.prototype.off = function() {
    return this._logger.remove();
  };

  WinstonLoggerWrapper.prototype.addFile = function(filepath) {
    return this._logger.add(winston.transports.File, {
      filename: filepath,
      handleExceptions: true
    });
  };

  return WinstonLoggerWrapper;

})();

/**
 * The logger class is providing a small interface to add logging capabilites to a given class
 * 
 * @class Logger
*/


Logger = (function() {
  Logger.prototype.Logger = true;

  Logger.prototype._constructor_ = function() {
    this._log = new WinstonLoggerWrapper();
    this._log.setClassName(this._selfClassName);
    return this._log.setObject(this);
  };

  function Logger() {
    this._constructor_();
  }

  /**
   * Get the logger class for external usage
   *
   * @for Logger
   * @method getLogger
   * @return {Logger} Logger class object
  */


  Logger.prototype.getLogger = function() {
    return this._log;
  };

  return Logger;

})();

module.exports = Logger;
