// Generated by CoffeeScript 1.6.2
var File, Logger, PluginList, ReadableEntity, Tools, TreeElement, async, fs, _PluginList;

async = require('async');

fs = require('fs');

Tools = require('./Tools');

Logger = require('./Logger');

ReadableEntity = require('./ReadableEntity');

TreeElement = require('./TreeElement');

File = require('./File');

/**
 * PluginList is a class containing multiple PluginDirectory classes.
 * This class is the root class for all plugins.
 * 
 * @class PluginList
 * @extends Logger
 * @extends ReadableEntity
 * @extends TreeElement
*/


PluginList = Tools.implementing(Logger, ReadableEntity, TreeElement, _PluginList = (function() {
  function _PluginList() {}

  return _PluginList;

})(), PluginList = (function() {
  function PluginList() {
    this._constructor_();
  }

  PluginList.prototype._constructor_ = function() {};

  return PluginList;

})());

module.exports = PluginList;
