// Generated by CoffeeScript 1.6.2
var File, Logger, ReadableEntity, SharedObjectManager, Tools, TreeElement, async, fs, _SharedObject;

async = require('async');

fs = require('fs');

Tools = require('./Tools');

Logger = require('./Logger');

ReadableEntity = require('./ReadableEntity');

TreeElement = require('./TreeElement');

File = require('./File');

/**
 * SharedObjectManager is a class to manager {SharedObject}s
 * 
 * @class SharedObjectManager
 * @extends Logger
 * @extends ReadableEntity
 * @extends TreeElement
*/


SharedObjectManager = Tools.implementing(Logger, ReadableEntity, _SharedObject = (function() {
  function _SharedObject() {}

  return _SharedObject;

})(), SharedObjectManager = (function() {
  SharedObjectManager.prototype._constructor_ = function() {};

  function SharedObjectManager() {
    this._constructor_();
  }

  return SharedObjectManager;

})());

module.exports = SharedObjectManager;
